module.exports = 
[
    {
        id:"101004",
        name:"Basic",
        title:"Basic",
        short:"The simple vanilla template",
        full:"Looking for a basic vanilla starter template for Bootstrap? This is the defacto starter template for Bootstrap 3 that includes a top navigation bar and centered block.",
        tags:["basic","starter","empty"],
        imgUrl:"http://www.bootply.com/assets/templates/101004.png",
        downloadUrl:"http://www.bootply.com/download/101004",
        sourceUrl:"http://www.bootply.com/101004",
        previewUrl:"http://www.bootply.com/render/101004",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
    {
        id:"100993",
        name:"Sidebar",
        title:"Sidebar",
        short:"Popular left sidebar layout",
        full:"This is a popular 2 column template for Bootstrap 3 that includes a left-side 33% width column, and 66% width content area.",
        tags:["sidebar","starter"],
        imgUrl:"http://www.bootply.com/assets/templates/100993.png",
        downloadUrl:"http://www.bootply.com/download/100993",
        sourceUrl:"http://www.bootply.com/100993",
        previewUrl:"http://www.bootply.com/render/100993",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
    {
        id:"94967",
        name:"FixedWidth",
        title:"Fixed Width",
        short:"Pixel-based container layout",
        full:"Bootstrap out-of-the-box uses a fluid or percentage-based container. Using a simple wrapper DIV you can easily create a fixed width (pixel-based) container as this template does.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/94967.png",
        downloadUrl:"http://www.bootply.com/download/94967",
        sourceUrl:"http://www.bootply.com/94967",
        previewUrl:"http://www.bootply.com/render/94967",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"75225",
        name:"Fixed Navbar",
        title:"Fixed Navbar",
        short:"Sticky top nav template",
        full:"A Basic Bootstrap template with fluid width and sticky top navigation.",
        tags:["starter","fixed","sticky","header","navbar"],
        imgUrl:"http://www.bootply.com/assets/templates/75225.png",
        downloadUrl:"http://www.bootply.com/download/75225",
        sourceUrl:"http://www.bootply.com/75225",
        previewUrl:"http://www.bootply.com/render/75225",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
    {
        id:"75231",
        name:"Sticky Footer",
        title:"Sticky Footer",
        short:"Footer always pushed to the bottom",
        full:"A simple Bootstrap template with a sticky footer that always stays on the bottom regardless of page content.",
        tags:["starter","fixed","sticky","footer"],
        imgUrl:"http://www.bootply.com/assets/templates/75231.png",
        downloadUrl:"http://www.bootply.com/download/75231",
        sourceUrl:"http://www.bootply.com/75231",
        previewUrl:"http://www.bootply.com/render/75231",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"73778",
        name:"Grid",
        title:"Grid",
        short:"Uses the powerful Bootstrap grid",
        full:"This template uses multiple grid columns and widths. Use this example to see how to control the Bootstrap grid behavior and breakpoints on different devices you can combine the large, small or tiny grid sizes. Use combinations of .col-xs-*, .col-sm-* and .col-lg-* to manipulate the horizontal and vertical display of elements on multiple devices.",
        tags:["starter","grid","responsive","stacking","collapse","mobile"],
        imgUrl:"http://www.bootply.com/assets/templates/73778.png",
        downloadUrl:"http://www.bootply.com/download/73778",
        sourceUrl:"http://www.bootply.com/73778",
        previewUrl:"http://www.bootply.com/render/73778",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"100983",
        name:"Affix Sidebar",
        title:"Affix Sidebar",
        short:"Sidebar like the Bootstrap docs",
        full:"Similar to the Bootstrap documentation, this template features a left-side nav that attaches once scrolling goes beyond a large top header with ad space.",
        tags:["starter","fixed","affix","sidebar","pin","scroll","scrollspy"],
        imgUrl:"http://www.bootply.com/assets/templates/100983.png",
        downloadUrl:"http://www.bootply.com/download/100983",
        sourceUrl:"http://www.bootply.com/100983",
        previewUrl:"http://www.bootply.com/render/100983",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.1.1",
        license:"MIT"
    },
	{
        id:"65566",
        name:"Full Example",
        title:"Full Example",
        short:"A complete Bootstrap template",
        full:"A Bootstrap template that exemplifies the Bootstrap CSS and many Bootstrap components such as buttons, tabs, panels, progress bars, pagination, labels and breadcrumbs.<p>This template makes a great Bootstrap test page for demonstration of CSS, elements and components.</p>",
        tags:["starter","example","complete","tabs","panel","progress","buttons","label","context"],
        imgUrl:"http://www.bootply.com/assets/templates/65566.png",
        downloadUrl:"http://www.bootply.com/download/65566",
        sourceUrl:"http://www.bootply.com/65566",
        previewUrl:"http://www.bootply.com/render/65566",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"101053",
        name:"Complex Navbar",
        title:"Complex Navbar",
        short:"Nav with buttons, text and form",
        full:"This Bootstrap layout will show you how to create a fixed top navbar with dropdowns, buttons, text and right-aligned search form.",
        tags:["starter","right","icon","navbar","search","form"],
        imgUrl:"http://www.bootply.com/assets/templates/101053.png",
        downloadUrl:"http://www.bootply.com/download/101053",
        sourceUrl:"http://www.bootply.com/101053",
        previewUrl:"http://www.bootply.com/render/101053",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"88026",
        name:"OffCanvas",
        title:"Off Canvas Sidebar",
        short:"Collapsing left sidebar",
        full:"A Bootstrap template with left sidebar that collapses off-canvas on smaller width devices like portrait tables and smartphones.",
        tags:["starter","responsive","off-canvas","toggle","sidebar","collapse","mobile"],
        imgUrl:"http://www.bootply.com/assets/templates/88026.png",
        downloadUrl:"http://www.bootply.com/download/88026",
        sourceUrl:"http://www.bootply.com/88026",
        previewUrl:"http://www.bootply.com/render/88026",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.1.1",
        license:"MIT"
    },
	{
		id:"97459",
        name:"Portfolio",
        title:"Portfolio",
        short:"Gallery Lightbox Thumbnails",
        full:"Use this as a basis for a portfolio or image gallery. The Bootstrap 3 modal and carousel are combined to create a lightbox for each image with previous / next navigation links inside the modal lightbox.",
        tags:["gallery","modal","lightbox","thumbnail","starter"],
        imgUrl:"http://www.bootply.com/assets/templates/97459.png",
        downloadUrl:"http://www.bootply.com/download/97459",
        sourceUrl:"http://www.bootply.com/97459",
        previewUrl:"http://www.bootply.com/render/97459",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"62603",
        name:"Slider",
        title:"Slider",
        short:"Intro page with Carousel",
        full:"A Bootstrap carousel example with full width images, overlay navbar and dot navigation. The page content has 3 feature content blocks, and long scrolling alternating left and right aligned content sections.",
        tags:["starter","slider","carousel","left","right","card"],
        imgUrl:"http://www.bootply.com/assets/templates/62603.png",
        downloadUrl:"http://www.bootply.com/download/62603",
        sourceUrl:"http://www.bootply.com/62603",
        previewUrl:"http://www.bootply.com/render/62603",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.0",
        license:"MIT"
    },
	{
        id:"101009",
        name:"Landing",
        title:"Landing Page",
        short:"Great startup launch page",
        full:"A Bootstrap landing or intro page example. This template features a centered header/logo, email form and social icons. Below the large header are 3 content blocks to highlight features.",
        tags:["starter","landing","launch","startup","email","center","form","intro"],
        imgUrl:"http://www.bootply.com/assets/templates/101009.png",
        downloadUrl:"http://www.bootply.com/download/101009",
        sourceUrl:"http://www.bootply.com/101009",
        previewUrl:"http://www.bootply.com/render/101009",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.2",
        license:"MIT"
    },
	{
        id:"101498",
        name:"Sign-In",
        title:"Sign In",
        short:"Clean modal login form",
        full:"A simple login / sign-in page using the Bootstrap 3 modal. This example is shown inline, but could also be used as a pop-up modal.",
        tags:["starter","signin","login","modal"],
        imgUrl:"http://www.bootply.com/assets/templates/101498.png",
        downloadUrl:"http://www.bootply.com/download/101498",
        sourceUrl:"http://www.bootply.com/101498",
        previewUrl:"http://www.bootply.com/render/101498",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"96937",
        name:"App",
        title:"App",
        short:"Gmail-style full height layout",
        full:"100% width app style template for Bootstrap. The content area and sidebar have independant scrollbars. The navbar has a left and right-aligned links.",
        tags:["starter","fixed","100%","full","scroll","scrollbars","app","gmail"],
        imgUrl:"http://www.bootply.com/assets/templates/96937.png",
        downloadUrl:"http://www.bootply.com/download/96937",
        sourceUrl:"http://www.bootply.com/96937",
        previewUrl:"http://www.bootply.com/render/96937",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.1.1",
        license:"MIT"
    },
	{
        id:"101499",
        name:"Blog",
        title:"Blog",
        short:"Ideal for articles and item lists",
        full:"A simple starter for a blog or article list. This template also features a navbar with search form, ad space, and a social button toolbar which uses Font Awesome fonts.",
        tags:["starter","ad","blog","list","font-awesome","search"],
        imgUrl:"http://www.bootply.com/assets/templates/101499.png",
        downloadUrl:"http://www.bootply.com/download/101499",
        sourceUrl:"http://www.bootply.com/101499",
        previewUrl:"http://www.bootply.com/render/101499",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"101506",
        name:"Portal",
        title:"Portal",
        short:"Multi-purpose modular design",
        full:"A versatile Bootstrap template with left/right sidebar, main article list and navbar search form.",
        tags:["starter","portal","search","navbar"],
        imgUrl:"http://www.bootply.com/assets/templates/101506.png",
        downloadUrl:"http://www.bootply.com/download/101506",
        sourceUrl:"http://www.bootply.com/101506",
        previewUrl:"http://www.bootply.com/render/101506",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"128936",
        name:"Dashboard",
        title:"Dashboard",
        short:"Dashboard with off-canvas sidebar",
        full:"This is a template for a admin, control panel or dashboard. This template has a collapsible sidebar menu, and a variety of panels that can be used as dashboard widgets.",
        tags:["starter","admin","dashboard","theme","sidebar","off-canvas","collapse"],
        imgUrl:"http://www.bootply.com/assets/templates/tmp_128936.png",
        downloadUrl:"http://www.bootply.com/download/128936",
        sourceUrl:"http://www.bootply.com/128936",
        previewUrl:"http://www.bootply.com/render/128936",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        bootstrapVersion:"3.1.1",
        license:"MIT"
    },
	{
        id:"90113",
        name:"Plus",
        title:"Google Plus",
        short:"Google+ style with cards",
        full:"Google+ inspired responsive starter template with 2 top navs, cards, fluid columns and flat design. The template has login modal pop-up, home menu, and layout toggle that switches the grid between 2 and 3 columns.",
        tags:["google","google-plus","theme","flat","toggle","cards"],
        imgUrl:"http://www.bootply.com/assets/templates/90113.png",
        downloadUrl:"http://www.bootply.com/download/90113",
        sourceUrl:"http://www.bootply.com/90113",
        previewUrl:"http://www.bootply.com/render/90113",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"91970",
        name:"Holo",
        title:"Holo",
        short:"Android inspired Bootstrap theme",
        full:"Android Holo theme inspired Bootstrap template with sidebar offcanvas nav, fluid columns and toggle switches. This is sleek, clean design utilizes the Droid Sans Google font.",
        tags:["theme","fixed","android","holo","off-canvas","flat","dark","switch"],
        imgUrl:"http://www.bootply.com/assets/templates/91970.png",
        downloadUrl:"http://www.bootply.com/download/91970",
        sourceUrl:"http://www.bootply.com/91970",
        previewUrl:"http://www.bootply.com/render/91970",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        bootstrapVersion:"3.0.3",
        license:"MIT"
    },
	{
        id:"85779",
        name:"Storystrap",
        title:"Storystrap",
        short:"Simple article list template",
        full:"A single column design that works well for articles, blog posts and content lists. This template features ad space, search form and social media buttons.",
        tags:["theme","social","blog","ads"],
        imgUrl:"http://www.bootply.com/assets/templates/85779.png",
        downloadUrl:"http://www.bootply.com/download/85779",
        sourceUrl:"http://www.bootply.com/85779",
        previewUrl:"http://www.bootply.com/render/85779",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT"
    },
	{
        id:"85861",
        name:"Dashboard",
        title:"Dashboard",
        short:"Control panel template",
        full:"This admin template for Bootstrap features a variety of tabular, form, progress and toolbox widgets in a multi-column responsive layout.",
        tags:["theme","admin","dashboard","tree"],
        imgUrl:"http://www.bootply.com/assets/templates/85861.png",
        downloadUrl:"http://www.bootply.com/download/85861",
        sourceUrl:"http://www.bootply.com/85861",
        previewUrl:"http://www.bootply.com/render/85861",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT"
    },
	{
        id:"69913",
        name:"Bootable",
        title:"Bootable",
        short:"3-column with sidebar",
        full:"A popular social media and tech news site was the inspiration for this 3-column sticky scrolling design.",
        tags:["news","theme","affix"],
        imgUrl:"http://www.bootply.com/assets/templates/69913.png",
        downloadUrl:"http://www.bootply.com/download/69913",
        sourceUrl:"http://www.bootply.com/69913",
        previewUrl:"http://www.bootply.com/render/69913",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT"
    },
	{
        id:"85746",
        name:"CapitalCity",
        title:"Capital City",
        short:"One page scrolling template",
        full:"Single page app style template with smooth scrolling nav, and centered content that make it ideal for a app launch or startup page.",
        tags:["theme","parallax","scroll","launch","startup","one-page"],
        imgUrl:"http://www.bootply.com/assets/templates/85746.png",
        downloadUrl:"http://www.bootply.com/download/85746",
        sourceUrl:"http://www.bootply.com/85746",
        previewUrl:"http://www.bootply.com/render/85746",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT"
    },
	{
        id:"69873",
        name:"Flathood",
        title:"Flathood",
        short:"Bold 2-column layout",
        full:"A popular tech news site was the inspiration for this 2-column bold, bright design. This template uses the Bootstrap affix plugin to pin the sidebar after scrolling past the top header.",
        tags:["fixed","affix","sidebar","news","theme","blog"],
        imgUrl:"http://www.bootply.com/assets/templates/69873.png",
        downloadUrl:"http://www.bootply.com/download/69873",
        sourceUrl:"http://www.bootply.com/69873",
        previewUrl:"http://www.bootply.com/render/69873",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT"
    },
	{
        id:"85850",
        name:"Admin",
        title:"Admin",
        short:"3 column control panel",
        full:"This is a starter template for a admin, control panel or dashboard. This template has a collapsible tree menu, and a variety of panels that can be used as dashboard widgets.",
        tags:["starter","admin","dashboard","theme","tree"],
        imgUrl:"http://www.bootply.com/assets/templates/85850.png",
        downloadUrl:"http://www.bootply.com/download/85850",
        sourceUrl:"http://www.bootply.com/85850",
        previewUrl:"http://www.bootply.com/render/85850",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT"
    },
	{
        id:"86704",
        name:"Basis",
        title:"Basis",
        short:"Minimal fixed sidebar layout",
        full:"A fresh, minimalist design that features a fixed left panel, and scrolling right content panel that works well for articles and blog posts.",
        tags:["theme","fixed","sidebar","minimal"],
        imgUrl:"http://www.bootply.com/assets/templates/86704.png",
        downloadUrl:"http://www.bootply.com/download/86704",
        sourceUrl:"http://www.bootply.com/86704",
        previewUrl:"http://www.bootply.com/render/86704",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT"
    },
	{
        id:"85657",
        name:"Greenfield",
        title:"Greenfield",
        short:"Bold single page scroller",
        full:"Ideal for a landing page, this template includes a smooth scrolling nav, and fixed background images to create a parallax style affect. The top nav menu items are activated as the content sections are scrolled to.",
        tags:["theme","launch","scrollspy","scroll","smooth"],
        imgUrl:"http://www.bootply.com/assets/templates/85657.png",
        downloadUrl:"http://www.bootply.com/download/85657",
        sourceUrl:"http://www.bootply.com/85657",
        previewUrl:"http://www.bootply.com/render/85657",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT"
    },
	{
        id:"88105",
        name:"Darkside",
        title:"Darkside",
        short:"Dark with off-canvas sidebar",
        full:"The deep gray layout features a sidebar drawer menu that responsively collapses off-canvas on smaller devices such as tablets and smartphones.<br>When the sidebar is collapsed, it can be toggled on so that it slides in from the left and consumes 40% of the screen width.<br>This template also includes a sticky bottom footer that stays at the bottom regardless of content height.",
        tags:["theme","fixed","dark","sidebar","collapse","off-canvas","mobile","toggle","footer","sticky"],
        responsive:true,
        imgUrl:"http://www.bootply.com/assets/templates/88105.png",
        downloadUrl:"http://www.bootply.com/download/88105",
        sourceUrl:"http://www.bootply.com/88105",
        previewUrl:"http://www.bootply.com/render/88105",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.3",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT"
    },
	{
        id:"96266",
        name:"Facebook",
        title:"Facebook",
        short:"Facebook-style collapsing sidebar",
        full:"<p>A Facebook inspired template and theme that features a responsive collapsible off-canvas sidebar.</p><p>When the sidebar is collapsed, it can be toggled with a chevron arrow so that it slides in from the left to 1/3 of the screen width.</p><p>This template also features a navbar search form, status post modal and content cards.</p>",
        tags:["theme","sidebar","facebook","off-canvas","toggle","search","modal"],
        responsive:true,
        imgUrl:"http://www.bootply.com/assets/templates/96266.png",
        downloadUrl:"http://www.bootply.com/download/96266",
        sourceUrl:"http://www.bootply.com/96266",
        previewUrl:"http://www.bootply.com/render/96266",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT"
    },
	{
        id:"88300",
        name:"5050",
        title:"5050",
        short:"Full width 2x2 grid",
        full:"A simple layout with fixed header and footer, and a centered 50% height and 50% width 2x2 grid.",
        tags:["theme","background","full","100%"],
        responsive:true,
        imgUrl:"http://www.bootply.com/assets/templates/88300.png",
        downloadUrl:"http://www.bootply.com/download/88300",
        sourceUrl:"http://www.bootply.com/88300",
        previewUrl:"http://www.bootply.com/render/88300",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        license:"MIT",
        licenseUrl:""
    },
	{
        id:"100702",
        name:"HappyScroll",
        title:"Happy Scroll",
        short:"One page parallax style",
        full:"A bold, bright Bootstrap template that features a centered fly-in navbar with sections that activate when scrolling. This template also includes a Google Maps contact section, social media buttons, sticky footer and fixed image background.",
        tags:["fixed","scrollspy","google-maps","map","sections","theme"],
        responsive:true,
        imgUrl:"http://www.bootply.com/assets/templates/100702.png",
        downloadUrl:"http://www.bootply.com/download/100702",
        sourceUrl:"http://www.bootply.com/100702",
        previewUrl:"http://www.bootply.com/render/100702",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.2",
        license:"MIT",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        licenseUrl:""
    },
	{
        id:"102931",
        name:"Firm",
        title:"The Firm",
        short:"Clean one page scrolling layout",
        full:"A long scrolling Bootstrap template with centered navbar and multiple vertical sections. The header contains a full screen image carousel with dot navigation. The center navbar attaches once the user scrolls beyond the carousel / slider. This template also includes a modal lightbox thumbnail viewer that is ideal for a portfolio or image gallery. The contact form address drives the integrated Google maps location.",
        tags:["theme","scroll","one-page","background","business","full","google-maps","map","lightbox","slider","gallery","navbar","affix","contact"],
        responsive:true,
        imgUrl:"http://www.bootply.com/assets/templates/102931.png",
        downloadUrl:"http://www.bootply.com/download/102931",
        sourceUrl:"http://www.bootply.com/102931",
        previewUrl:"http://www.bootply.com/render/102931",
        author:"Bootply.com",
        authorUrl:"http://www.bootply.com/templates",
        bootstrapVersion:"3.0.2",
        license:"MIT",
        avatar:"https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905.jpeg",
        licenseUrl:""
    },
    {
        name:"Cerulean",
        title:"Cerulean Theme",
        short:"A Calm, Blue Sky",
        full:"A free theme from Bootswatch",
        responsive:true,
        tags:["bootswatch","theme"],
        imgUrl:"http://bootswatch.com/cerulean/thumbnail.png",
        downloadUrl:"http://bootswatch.com/cerulean/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/cerulean/",
        previewUrl:"http://bootswatch.com/cerulean/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Cosmo",
        title:"Cosmo Theme",
        short:"An Ode to Metro",
        full:"A free theme from Bootswatch",
        tags:["bootswatch","theme"],
        imgUrl:"http://bootswatch.com/cosmo/thumbnail.png",
        downloadUrl:"http://bootswatch.com/cosmo/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/cosmo/",
        previewUrl:"http://bootswatch.com/cosmo/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Amelia",
        title:"Amelia Theme",
        short:"Sweet and cheery",
        full:"A free theme from Bootswatch",
        tags:["bootswatch","theme"],
        imgUrl:"http://bootswatch.com/amelia/thumbnail.png",
        downloadUrl:"http://bootswatch.com/amelia/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/amelia/",
        previewUrl:"http://bootswatch.com/amelia/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Cyborg",
        title:"Cyborg Theme",
        short:"Jet black and electric blue",
        full:"A free theme from Bootswatch",
        tags:["bootswatch","theme"],
        imgUrl:"http://bootswatch.com/cyborg/thumbnail.png",
        downloadUrl:"http://bootswatch.com/cyborg/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/cyborg/",
        previewUrl:"http://bootswatch.com/cyborg/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Flatly",
        title:"Flatly Theme",
        short:"Flat and modern",
        full:"A free theme from Bootswatch",
        tags:["bootswatch","theme","flat"],
        imgUrl:"http://bootswatch.com/flatly/thumbnail.png",
        downloadUrl:"http://bootswatch.com/flatly/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/flatly/",
        previewUrl:"http://bootswatch.com/flatly/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Readable",
        title:"Readable Theme",
        short:"Optimized for readability",
        full:"A free theme from Bootswatch",
        tags:["bootswatch","theme","readable"],
        imgUrl:"http://bootswatch.com/readable/thumbnail.png",
        downloadUrl:"http://bootswatch.com/readable/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/readable/",
        previewUrl:"http://bootswatch.com/readable/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Journal",
        title:"Journal Theme",
        short:"Crisp like a new paper",
        full:"A free theme from Bootswatch",
        tags:["bootswatch","theme"],
        imgUrl:"http://bootswatch.com/journal/thumbnail.png",
        downloadUrl:"http://bootswatch.com/journal/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/journal/",
        previewUrl:"http://bootswatch.com/journal/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Simplex",
        title:"Simplex Theme",
        short:"Mini and minimalist",
        full:"A free theme from Bootswatch",
        tags:["bootswatch","theme","minimal"],
        imgUrl:"http://bootswatch.com/simplex/thumbnail.png",
        downloadUrl:"http://bootswatch.com/simplex/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/simplex/",
        previewUrl:"http://bootswatch.com/simplex/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Slate",
        title:"Slate Theme",
        short:"Shades of gunmetal gray",
        full:"A free theme from Bootswatch",
        tags:["bootswatch","theme"],
        imgUrl:"http://bootswatch.com/slate/thumbnail.png",
        downloadUrl:"http://bootswatch.com/slate/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/slate/",
        previewUrl:"http://bootswatch.com/slate/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Spacelab",
        title:"Spacelab Theme",
        short:"Silvery and sleek",
        full:"A free theme from Bootswatch. This theme includes the complete Bootstrap baseline so it replaces your existing bootstrap.css.",
        tags:["bootswatch","theme"],
        imgUrl:"http://bootswatch.com/spacelab/thumbnail.png",
        downloadUrl:"http://bootswatch.com/spacelab/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/spacelab/",
        previewUrl:"http://bootswatch.com/spacelab/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"United",
        title:"United Theme",
        short:"Ubuntu orange and unique font",
        full:"A free theme from Bootswatch. This theme includes the complete Bootstrap baseline so it replaces your existing bootstrap.css.",
        tags:["bootswatch","theme"],
        imgUrl:"http://bootswatch.com/united/thumbnail.png",
        downloadUrl:"http://bootswatch.com/united/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/united/",
        previewUrl:"http://bootswatch.com/united/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Yeti",
        title:"Yeti Theme",
        short:"A friendly foundation",
        full:"A free theme from Bootswatch. This theme includes the complete Bootstrap baseline so it replaces your existing bootstrap.css.",
        tags:["bootswatch","theme","foundation","flat"],
        imgUrl:"http://bootswatch.com/yeti/thumbnail.png",
        downloadUrl:"http://bootswatch.com/yeti/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/yeti/",
        previewUrl:"http://bootswatch.com/yeti/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.0.3",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Lumen",
        title:"Lumen Theme",
        short:"Light and shadow",
        full:"A free theme from Bootswatch. This theme includes the complete Bootstrap baseline so it replaces your existing bootstrap.css.",
        tags:["bootswatch","theme","shadow","white","light"],
        imgUrl:"http://bootswatch.com/lumen/thumbnail.png",
        downloadUrl:"http://bootswatch.com/lumen/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/lumen/",
        previewUrl:"http://bootswatch.com/lumen/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.1.0",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Superhero",
        title:"Superhero Theme",
        short:"Brave and blue",
        full:"A free theme from Bootswatch. This theme includes the complete Bootstrap baseline so it replaces your existing bootstrap.css.",
        tags:["bootswatch","theme","blue","dark"],
        imgUrl:"http://bootswatch.com/superhero/thumbnail.png",
        downloadUrl:"http://bootswatch.com/superhero/bootstrap.min.css",
        sourceUrl:"http://bootswatch.com/superhero/",
        previewUrl:"http://bootswatch.com/superhero/",
        author:"Bootswatch",
        authorUrl:"http://bootswatch.com/",
        bootstrapVersion:"3.1.0",
        license:"Apache",
        avatar:"https://pbs.twimg.com/profile_images/3387741863/b048a3aa0b489981587c20cc813f57e1.jpeg",
        licenseUrl:""
    },
    {
        name:"Land",
        title:"Land Template",
        short:"Landing page with sign up form",
        full:"A free template from Coverstrap that makes a nice landing page with a mailing list sign up form.",
        tags:["coverstrap","template","landing","launch","form"],
        imgUrl:"http://coverstrap.com/img/preview-land.b5b358f38b77dddbdecbbf728aab92af8c9c8f10.jpg",
        downloadUrl:"http://coverstrap.com/downloads/land.zip",
        sourceUrl:"http://coverstrap.com/previews/land.html",
        previewUrl:"http://coverstrap.com/previews/land.html",
        author:"Coverstrap",
        authorUrl:"http://coverstrap.com/",
        bootstrapVersion:"3.0.3",
        license:"CC0",
        avatar:"https://pbs.twimg.com/profile_images/1344367318/profile-small_bigger.png",
        licenseUrl:""
    },
    {
        name:"Strapped",
        title:"Strapped Template",
        short:"Single page template",
        full:"A single page template from Coverstrap with a jumbotron, features, tour and about sections. Utilizes Glyphicons for showcasing features.",
        tags:["coverstrap","template","jumbotron","launch","glyphicons","single-page","carousel","slider","one-page"],
        imgUrl:"http://coverstrap.com/img/preview-strapped.b5b358f38b77dddbdecbbf728aab92af8c9c8f10.jpg",
        downloadUrl:"http://coverstrap.com/downloads/strapped.zip",
        sourceUrl:"http://coverstrap.com/previews/strapped.html",
        previewUrl:"http://coverstrap.com/previews/strapped.html",
        author:"Coverstrap",
        authorUrl:"http://coverstrap.com/",
        bootstrapVersion:"3.0.3",
        license:"CC0",
        avatar:"https://pbs.twimg.com/profile_images/1344367318/profile-small_bigger.png",
        licenseUrl:""
    },
    {
        name:"Laptop",
        title:"Laptop Template",
        short:"Template with Macbook carousel",
        full:"A free template from Coverstrap to show off photos of your product on a Macbook Pro screen. Photos are shown via the standard Bootstrap carousel inside the Macbook screen.",
        tags:["coverstrap","template","portfolio","gallery","photos","mac","macbook","slider","screen","carousel"],
        imgUrl:"http://coverstrap.com/img/preview-laptop.b5b358f38b77dddbdecbbf728aab92af8c9c8f10.jpg",
        downloadUrl:"http://coverstrap.com/downloads/laptop.zip",
        sourceUrl:"http://coverstrap.com/previews/laptop.html",
        previewUrl:"http://coverstrap.com/previews/laptop.html",
        author:"Coverstrap",
        authorUrl:"http://coverstrap.com/",
        bootstrapVersion:"3.0.3",
        license:"CC0",
        avatar:"https://pbs.twimg.com/profile_images/1344367318/profile-small_bigger.png",
        licenseUrl:""
    },
    {
        name:"Media",
        title:"Media Template",
        short:"Show off photography",
        full:"Another Bootstrap template from Coverstrap that is ideal for websites which show off a lot of photos. Stock photos provided by Unsplash. This template also has a sleek block heading text that overlays the jumbotron.",
        tags:["coverstrap","template","portfolio","gallery","photos","unsplash","stock","overlay","jumbotron"],
        imgUrl:"http://coverstrap.com/img/preview-media.b5b358f38b77dddbdecbbf728aab92af8c9c8f10.jpg",
        downloadUrl:"http://coverstrap.com/downloads/media.zip",
        sourceUrl:"http://coverstrap.com/previews/media.html",
        previewUrl:"http://coverstrap.com/previews/media.html",
        author:"Coverstrap",
        authorUrl:"http://coverstrap.com/",
        bootstrapVersion:"3.0.3",
        license:"CC0",
        avatar:"https://pbs.twimg.com/profile_images/1344367318/profile-small_bigger.png",
        licenseUrl:""
    },
    {
        name:"Lighter",
        title:"Lighter Template",
        short:"Simple with light colors",
        full:"Another Bootstrap template from Coverstrap that very simple template with only light colors. Includes features, tour, FAQs, and about sections.",
        tags:["coverstrap","template","simple","clean","light","minimal"],
        imgUrl:"http://coverstrap.com/img/preview-lighter.b5b358f38b77dddbdecbbf728aab92af8c9c8f10.jpg",
        downloadUrl:"http://coverstrap.com/downloads/lighter.zip",
        sourceUrl:"http://coverstrap.com/previews/lighter.html",
        previewUrl:"http://coverstrap.com/previews/lighter.html",
        author:"Coverstrap",
        authorUrl:"http://coverstrap.com/",
        bootstrapVersion:"3.0.3",
        license:"CC0",
        avatar:"https://pbs.twimg.com/profile_images/1344367318/profile-small_bigger.png",
        licenseUrl:""
    },
    {
        name:"Flatty",
        title:"Flatty",
        short:"Flat landing page",
        full:"Flatty is a free Bootstrap template from BlackTie that is a flat landing page designed to show your next app, site or product. With a fresh style & minimal design, you can now show your product with style.",
        tags:["blacktie","theme","flat","landing","launch","product","startup","app"],
        imgUrl:"http://www.blacktie.co/blog/wp-content/uploads/2013/12/flatty.png",
        downloadUrl:"http://bit.ly/18QS8X2",
        sourceUrl:"http://www.blacktie.co/2013/12/flatty-app-landing-page/",
        previewUrl:"http://www.blacktie.co/demo/flatty/",
        author:"BlackTie",
        authorUrl:"http://www.blacktie.co",
        bootstrapVersion:"3.0.3",
        license:"CC0",
        avatar:"https://pbs.twimg.com/profile_images/427947974044315648/DYrSsfHE.png",
        licenseUrl:""
    },
    {
        name:"Bolt",
        title:"Bolt",
        short:"Flat one page theme",
        full:"Bolt is a Bootstrap template from BlackTie. Bolt is an elegant option to show your work and contact information. A clean design with focus on information. Includes Font Awesome 4.0.3 &amp; Chart.js script. The overall design was inspired by the awesome work of Jack Lalley. Dribbble shots used in this demo comes from the designer Justin Mezzell.",
        tags:["blacktie","theme","flat","chart","portfolio","one-page"],
        imgUrl:"http://www.blacktie.co/blog/wp-content/uploads/2013/11/bolt.png",
        downloadUrl:"http://bit.ly/1eve3Er",
        sourceUrl:"http://www.blacktie.co/2013/11/bolt-flat-one-page-theme/",
        previewUrl:"http://blacktie.co/demo/bolt/",
        author:"BlackTie",
        authorUrl:"http://www.blacktie.co",
        bootstrapVersion:"3.0.3",
        license:"CC0",
        avatar:"https://pbs.twimg.com/profile_images/427947974044315648/DYrSsfHE.png",
        licenseUrl:""
    },
    {
        name:"Small",
        title:"Small",
        short:"Dribble portfolio Bootstrap theme",
        full:"Small is a Bootstrap template from BlackTie. Small is a little theme focused in your latest dribbble shots. Thanks to the jibbble script, this theme allows you to show 8 shots on the front page. Works excellent as a vCard option.",
        tags:["blacktie","theme","dribble","portfolio","one-page"],
        imgUrl:"http://www.blacktie.co/blog/wp-content/uploads/2013/11/small.png",
        downloadUrl:"http://bit.ly/1fEate0",
        sourceUrl:"http://www.blacktie.co/2013/11/small-dribbble-portfolio-theme/",
        previewUrl:"http://blacktie.co/demo/small/",
        author:"BlackTie",
        authorUrl:"http://www.blacktie.co",
        bootstrapVersion:"3.0.2",
        license:"CC0",
        avatar:"https://pbs.twimg.com/profile_images/427947974044315648/DYrSsfHE.png",
        licenseUrl:""
    },
    {
        name:"Minimal",
        title:"Minimal Dark",
        short:"Dark Bootstrap theme",
        full:"Minimal is a Bootstrap template from BlackTie. Minimal is a simple and small theme. Ideal for a contact page or minimal site. This theme was designed for those wanting something different more than the habitual information page.",
        tags:["blacktie","theme","dark","contact","minimal"],
        imgUrl:"http://www.blacktie.co/blog/wp-content/uploads/2013/10/minimal.png",
        downloadUrl:"http://bit.ly/1h1qJay",
        sourceUrl:"http://www.blacktie.co/2013/10/minimal-dark-bootstrap-3-theme/",
        previewUrl:"http://blacktie.co/demo/minimal",
        author:"BlackTie",
        authorUrl:"http://www.blacktie.co",
        bootstrapVersion:"3.0.0",
        license:"CC0",
        avatar:"https://pbs.twimg.com/profile_images/427947974044315648/DYrSsfHE.png",
        licenseUrl:""
    },
    {
        name:"Munter",
        title:"Munter",
        short:"One page theme",
        full:"Munter is another Bootstrap template from BlackTie. Munter is a very handsome Bootstrap 3 theme with a centered navbar. Comes with beautiful features like a fixed arrows navigation, a nice portfolio showcase and a smooth scroll.",
        tags:["blacktie","theme","smooth","one-page","scroll","center","navbar"],
        imgUrl:"http://www.blacktie.co/blog/wp-content/uploads/2013/10/munter.png",
        downloadUrl:"http://bit.ly/17549aE",
        sourceUrl:"http://www.blacktie.co/2013/10/munter-one-page-theme/",
        previewUrl:"http://blacktie.co/demo/munter",
        author:"BlackTie",
        authorUrl:"http://www.blacktie.co",
        bootstrapVersion:"3.0.0",
        license:"CC0",
        avatar:"https://pbs.twimg.com/profile_images/427947974044315648/DYrSsfHE.png",
        licenseUrl:""
    },
    {
        name:"Siimple",
        title:"Siimple",
        short:"Landing page",
        full:"Siimple is a free Bootstrap template from BootstrapTaste. This above the fold content is the main key of ‘Siimple’ template. You can use it for app showcase, selling single product or capture potential customer via newsletter / sign-up form. Its a really simple template but very powerful landing page.",
        tags:["bootstraptaste","theme","one-page","background-image","photo","landing"],
        imgUrl:"http://bootstraptaste.com/wp-content/uploads/2014/02/siimple-550-500x500.jpg",
        downloadUrl:"http://bootstraptaste.com/theme/siimple/",
        sourceUrl:"http://bootstraptaste.com/free-bootstrap-landing-page/",
        previewUrl:"http://bootstraptaste.com/theme/siimple/",
        author:"BootstrapTaste",
        authorUrl:"http://www.bootstraptaste.com",
        bootstrapVersion:"3.0.0",
        license:"freeware",
        avatar:"https://pbs.twimg.com/profile_images/429318798210916352/1Szn2_gT_bigger.jpeg",
        licenseUrl:""
    },
    {
        name:"Amoeba",
        title:"Amoeba",
        short:"One pager",
        full:"Amoeba is a free Bootstrap template from BootstrapTaste. Amoeba is one page site template built from Bootstrap 3 with modern flat style also coming with lot of premium features.",
        tags:["bootstraptaste","theme","one-page","background-image","flat","landing"],
        imgUrl:"http://bootstraptaste.com/wp-content/uploads/2014/01/amoeba-550-500x500.jpg",
        downloadUrl:"http://bootstraptaste.com/theme/amoeba/",
        sourceUrl:"http://bootstraptaste.com/free-one-page-bootstrap-template-amoeba/",
        previewUrl:"http://bootstraptaste.com/theme/amoeba/",
        author:"BootstrapTaste",
        authorUrl:"http://www.bootstraptaste.com",
        bootstrapVersion:"3.0.0",
        license:"freeware",
        avatar:"https://pbs.twimg.com/profile_images/429318798210916352/1Szn2_gT_bigger.jpeg",
        licenseUrl:""
    },
    {
        name:"Mamba",
        title:"Mamba",
        short:"One pager",
        full:"Mamba is a free Bootstrap template from BootstrapTaste. Mamba is a simple &amp; flat one page Bootstrap template, suitable for creative profiles. Includes a minimal navigation menu, smooth scroll and pure css lightbox on portfolio images.",
        tags:["bootstraptaste","theme","one-page","background-image","blue","flat"],
        imgUrl:"http://bootstraptaste.com/wp-content/uploads/2014/02/Mamba-Free-Bootstrap-3-one-page-template-2014-02-26-23-00-47-500x500.png",
        downloadUrl:"http://bootstraptaste.com/download-theme/87/",
        sourceUrl:"http://bootstraptaste.com/mamba-one-page-bootstrap-template-free/",
        previewUrl:"http://bootstraptaste.com/theme/mamba/",
        author:"BootstrapTaste",
        authorUrl:"http://www.bootstraptaste.com",
        bootstrapVersion:"3.1.1",
        license:"freeware",
        avatar:"https://pbs.twimg.com/profile_images/429318798210916352/1Szn2_gT_bigger.jpeg",
        licenseUrl:""
    },
    {
        name:"Magister",
        title:"Magister",
        short:"Single-page portfolio template",
        full:"Magister is a free, responsive, single-page Bootstrap template by GetTemplate. Ideal choice for personal or 'Coming soon' landing page.",
        tags:["gettemplate", "theme", "background", "one-page", "center", "portfolio"],
        imgUrl:"http://www.gettemplate.com/content/images/magister-large.jpg",
        downloadUrl:"http://bit.ly/1c8ihUV",
        sourceUrl:"http://www.gettemplate.com",
        previewUrl:"http://www.gettemplate.com/demo/magister/",
        author:"GetTemplate.com",
        authorUrl:"http://www.gettemplate.com",
        bootstrapVersion:"3.0.3",
        avatar:"http://www.gettemplate.com/content/images/gt.png",
        license:"CC Attribution",
        licenseUrl:"http://creativecommons.org/licenses/by/3.0/"
    },
    {
        name:"AdminLTE",
        title:"AdminLTE",
        short:"Admin dashboard template",
        full:"A free premium admin dashboard and control panel theme by Almsaeed Studio.",
        tags:["admin", "theme", "dashboard", "control-panel"],
        imgUrl:"http://www.daveismyname.com/system/ckeditor/elFinder/files/images/blog/design/adminlte-dashboard.png",
        downloadUrl:"http://almsaeedstudio.com/download/AdminLTE-master",
        sourceUrl:"https://github.com/almasaeed2010/AdminLTE/",
        previewUrl:"http://almsaeedstudio.com/preview",
        author:"Almsaeed Studio",
        authorUrl:"http://almsaeedstudio.com/",
        bootstrapVersion:"3.0.3",
        avatar:"https://pbs.twimg.com/profile_images/378800000050649381/41e2b37e68cdb7b6ace31ef6be3f093d.jpeg",
        license:"MIT",
        licenseUrl:""
    },
    {
        name:"devoops",
        title:"DevOOPS",
        short:"Dashboard theme",
        full:"DevOOPS is free admin dashboard theme by nnmware.",
        tags:["admin", "theme", "dashboard", "control-panel"],
        imgUrl:"http://devoops.me/img/devoops_screen.jpg",
        downloadUrl:"http://devoops.me/themes/devoops/devoops.zip",
        sourceUrl:"https://github.com/devoopsme/devoops",
        previewUrl:"http://devoops.me/themes/devoops/",
        author:"nnmware",
        authorUrl:"http://devoops.me/",
        bootstrapVersion:"3.1.0",
        avatar:"https://avatars0.githubusercontent.com/u/1585671?s=460",
        license:"GPL",
        licenseUrl:""
    },
    {
        name:"firmasite",
        title:"FirmaSite",
        short:"Wordpress theme",
        full:"A free Bootstrap wordpress theme by FirmaSite. This is a 2 column layout that works well for a blog or article list next to a multi-purpose sidebar.",
        tags:["wordpress", "theme", "respsonive", "blog", "sidebar"],
        imgUrl:"http://theme.firmasite.com/wp-content/uploads/2013/11/firmasite.jpg",
        downloadUrl:"http://wordpress.org/themes/download/firmasite.1.3.2.1.zip",
        sourceUrl:"http://demo.theme.firmasite.com/",
        previewUrl:"http://demo.theme.firmasite.com/",
        author:"FirmaSite",
        authorUrl:"http://theme.firmasite.com/",
        bootstrapVersion:"3.1.1",
        avatar:"https://pbs.twimg.com/profile_images/378800000021852655/d9c03cdd3feea0ce0036962483949f3c.png",
        license:"GPLv3",
        licenseUrl:"http://www.gnu.org/licenses/gpl.txt"
    }
]