module.exports = 
[
    {
        id:"101004",
        name:"Basic",
        title:"Basic",
        short:"The simple vanilla template",
        full:"Looking for a basic vanilla starter template for Bootstrap? This is the defacto starter template for Bootstrap 3 that includes a top navigation bar and centered block.",
        tags:["basic","starter","empty"],
        imgUrl:"http://www.bootply.com/assets/templates/101004.png",
        downloadUrl:"http://bootply.com/download/101004",
        sourceUrl:"http://bootply.com/101004",
        previewUrl:"http://bootply.com/render/101004",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
    {
        id:"100993",
        name:"Sidebar",
        title:"Sidebar",
        short:"Popular left column layout",
        full:"This is a popular 2 column template for Bootstrap 3 that includes a left-side 33% width column, and 66% width content area.",
        tags:["sidebar","starter"],
        imgUrl:"http://www.bootply.com/assets/templates/100993.png",
        downloadUrl:"http://bootply.com/download/100993",
        sourceUrl:"http://bootply.com/100993",
        previewUrl:"http://bootply.com/render/100993",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
    {
        id:"94967",
        name:"Fixed_Width",
        title:"Fixed Width",
        short:"Pixel-based container layout",
        full:"Bootstrap out-of-the-box uses a fluid or percentage-based container. Using a simple wrapper DIV you can easily create a fixed (ie:pixel-based) width container as this template does.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/94967.png",
        downloadUrl:"http://bootply.com/download/94967",
        sourceUrl:"http://bootply.com/94967",
        previewUrl:"http://bootply.com/render/94967",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"75225",
        name:"Fixed Navbar",
        title:"Fixed Navbar",
        short:"Sticky top nav template",
        full:"A Basic Bootstrap template with fluid width and sticky top navigation.",
        tags:["starter","fixed","sticky","header","navbar"],
        imgUrl:"http://bootply.com/assets/templates/75225.png",
        downloadUrl:"http://bootply.com/download/75225",
        sourceUrl:"http://bootply.com/75225",
        previewUrl:"http://bootply.com/render/75225",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
    {
        id:"75231",
        name:"Sticky Footer",
        title:"Sticky Footer",
        short:"Footer always pushed to the bottom",
        full:"A simple Bootstrap template with a sticky footer that always stays on the bottom regardless of page content.",
        tags:["starter","fixed","sticky","footer"],
        imgUrl:"http://www.bootply.com/assets/templates/75231.png",
        downloadUrl:"http://bootply.com/download/75231",
        sourceUrl:"http://bootply.com/75231",
        previewUrl:"http://bootply.com/render/75231",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"73778",
        name:"Grid",
        title:"Grid",
        short:"Demonstrates the powerful Bootstrap grid",
        full:"This template uses multiple grid columns and widths. Use this example to see how to control the Bootstrap grid behavior and breakpoints on different devices you can combine the large, small or tiny grid sizes. Use combinations of .col-xs-*, .col-sm-* and .col-lg-* to manipulate the horizontal and vertical display of elements on multiple devices.",
        tags:["starter","grid","responsive","stacking","collapse","mobile"],
        imgUrl:"http://www.bootply.com/assets/templates/73778.png",
        downloadUrl:"http://bootply.com/download/73778",
        sourceUrl:"http://bootply.com/73778",
        previewUrl:"http://bootply.com/render/73778",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"100983",
        name:"Affix Sidebar - /assets/templates/100983.png",
        title:"Affix Sidebar",
        short:"Sidebar like the Bootstrap docs",
        full:"Similar to the Bootstrap documentation, this template features a left-side nav that attaches once scrolling goes beyond a large top header with ad space.",
        tags:["starter","fixed","affix","sidebar","pin"],
        imgUrl:"http://www.bootply.com/assets/templates/100983.png",
        downloadUrl:"http://bootply.com/download/100983",
        sourceUrl:"http://bootply.com/100983",
        previewUrl:"http://bootply.com/render/100983",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"65566",
        name:"Full Example - /assets/templates/65566.png",
        title:"Full Example",
        short:"A complete Bootstrap template",
        full:"A Bootstrap template that exemplifies the Bootstrap CSS and many Bootstrap components such as buttons, tabs, panels, progress bars, pagination, labels and breadcrumbs.<p>This template makes a great Bootstrap test page for demonstration of CSS, elements and components.</p>",
        tags:["starter","example","complete","tabs","panel","progress","buttons","label","context"],
        imgUrl:"http://www.bootply.com/assets/templates/65566.png",
        downloadUrl:"http://bootply.com/download/65566",
        sourceUrl:"http://bootply.com/65566",
        previewUrl:"http://bootply.com/render/65566",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"101053",
        name:"Complex Navbar - /assets/templates/101053.png",
        title:"Complex Navbar",
        short:"Nav with buttons, text and form",
        full:"This Bootstrap layout will show you how to create a fixed top navbar with dropdowns, buttons, text and right-aligned search form.",
        tags:["starter","right","icon","navbar","search"],
        imgUrl:"http://www.bootply.com/assets/templates/101053.png",
        downloadUrl:"http://bootply.com/download/101053",
        sourceUrl:"http://bootply.com/101053",
        previewUrl:"http://bootply.com/render/101053",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"88026",
        name:"OffCanvas",
        title:"Off Canvas Sidebar",
        short:"Collapsing left sidebar",
        full:"A Bootstrap template with left sidebar that collapses off-canvas on smaller width devices like portrait tables and smartphones.",
        tags:["starter","responsive","off-canvas","toggle"],
        imgUrl:"http://www.bootply.com/assets/templates/88026.png",
        downloadUrl:"http://bootply.com/download/88026",
        sourceUrl:"http://bootply.com/88026",
        previewUrl:"http://bootply.com/render/88026",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
		id:"97459",
        name:"Portfolio",
        title:"Portfolio",
        short:"Gallery Lightbox Thumbnails",
        full:"Use this as a basis for a portfolio or image gallery. The Bootstrap 3 modal and carousel are combined to create a lightbox for each image with previous / next navigation links inside the modal lightbox.",
        tags:["gallery","modal","lightbox","thumbnail","starter"],
        imgUrl:"http://www.bootply.com/assets/templates/97459.png",
        downloadUrl:"http://bootply.com/download/97459",
        sourceUrl:"http://bootply.com/97459",
        previewUrl:"http://bootply.com/render/97459",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"62603",
        name:"Slider",
        title:"Slider",
        short:"Intro page with Carousel",
        full:"A Bootstrap carousel example with full width images, overlay navbar and dot navigation. The page content has 3 feature content blocks, and long scrolling alternating left and right aligned content sections.",
        tags:["starter","slider","carousel","left","right","card"],
        imgUrl:"http://www.bootply.com/assets/templates/62603.png",
        downloadUrl:"http://bootply.com/download/62603",
        sourceUrl:"http://bootply.com/62603",
        previewUrl:"http://bootply.com/render/62603",
        author:"Bootply.com",
        bootstrapVersion:"3.0.0"
    },
	{
        id:"101009",
        name:"Landing",
        title:"Landing Page",
        short:"Great startup launch page",
        full:"A Bootstrap landing or intro page example. This template features a centered header/logo, email form and social icons. Below the large header are 3 content blocks to highlight features.",
        tags:["starter","landing","launch","startup","email","center","form","intro"],
        imgUrl:"http://www.bootply.com/assets/templates/101009.png",
        downloadUrl:"http://bootply.com/download/101009",
        sourceUrl:"http://bootply.com/101009",
        previewUrl:"http://bootply.com/render/101009",
        author:"Bootply.com",
        bootstrapVersion:"3.0.2"
    },
	{
        id:"101498",
        name:"Sign-In",
        title:"Sign In",
        short:"Clean modal login form",
        full:"A simple login / sign-in page using the Bootstrap 3 modal. This example is shown inline, but could also be used as a pop-up modal.",
        tags:["starter","signin","login","modal"],
        imgUrl:"http://www.bootply.com/assets/templates/101498.png",
        downloadUrl:"http://bootply.com/download/101498",
        sourceUrl:"http://bootply.com/101498",
        previewUrl:"http://bootply.com/render/101498",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"96937",
        name:"App",
        title:"App",
        short:"Gmail-style full height layout",
        full:"100% width app style template for Bootstrap. The content area and sidebar have independant scrollbars. The navbar has a left and right-aligned links.",
        tags:["starter","fixed","100%","full","scroll","scrollbars","app","gmail"],
        imgUrl:"http://www.bootply.com/assets/templates/96937.png",
        downloadUrl:"http://bootply.com/download/96937",
        sourceUrl:"http://bootply.com/96937",
        previewUrl:"http://bootply.com/render/96937",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"101499",
        name:"Blog",
        title:"Blog",
        short:"Ideal for articles and item lists",
        full:"A simple starter for a blog or article list. This template also features a navbar with search form, ad space, and a social button toolbar which uses Font Awesome fonts.",
        tags:["starter","ad","blog","list","font-awesome","search"],
        imgUrl:"http://www.bootply.com/assets/templates/101499.png",
        downloadUrl:"http://bootply.com/download/101499",
        sourceUrl:"http://bootply.com/101499",
        previewUrl:"http://bootply.com/render/101499",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"101506",
        name:"Portal",
        title:"Portal",
        short:"Multi-purpose modular design",
        full:"A versatile Bootstrap template with left/right sidebar, main article list and navbar search form.",
        tags:["starter","portal","search","navbar"],
        imgUrl:"http://www.bootply.com/assets/templates/101506.png",
        downloadUrl:"http://bootply.com/download/101506",
        sourceUrl:"http://bootply.com/101506",
        previewUrl:"http://bootply.com/render/101506",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"90113",
        name:"Plus",
        title:"Plus",
        short:"Google+ style with cards",
        full:"Google+ inspired responsive starter template with 2 top navs, cards, fluid columns and flat design. The template has login modal pop-up, home menu, and layout toggle that switches the grid between 2 and 3 columns.",
        tags:["google","google-plus","theme","flat","toggle","cards"],
        imgUrl:"http://www.bootply.com/assets/templates/90113.png",
        downloadUrl:"http://bootply.com/download/90113",
        sourceUrl:"http://bootply.com/90113",
        previewUrl:"http://bootply.com/render/90113",
        author:"Bootply.com"
    },
	{
        id:"91970",
        name:"Holo",
        title:"Holo",
        short:"Android inspired Bootstrap theme",
        full:"Android Holo theme inspired Bootstrap template with sidebar offcanvas nav, fluid columns and toggle switches. This is sleek, clean design utilizes the Droid Sans Google font.",
        tags:["theme","fixed","android","holo","off-canvas","flat","dark","switch"],
        imgUrl:"http://bootply.com/assets/templates/91970.png",
        downloadUrl:"http://bootply.com/download/91970",
        sourceUrl:"http://bootply.com/91970",
        previewUrl:"http://bootply.com/render/91970",
        author:"Bootply.com"
    },
	{
        id:"85779",
        name:"Storystrap",
        title:"Storystrap",
        short:"Simple article list template",
        full:"A single column design that works well for articles, blog posts and content lists. This template features ad space, search form and social media buttons.",
        tags:["theme","social","blog","ads"],
        imgUrl:"http://www.bootply.com/assets/templates/85779.png",
        downloadUrl:"http://bootply.com/download/85779",
        sourceUrl:"http://bootply.com/85779",
        previewUrl:"http://bootply.com/render/85779",
        author:"Bootply.com"
    },
	{
        id:"85861",
        name:"Dashboard",
        title:"Dashboard",
        short:"Control panel template",
        full:"This admin template for Bootstrap features a variety of tabular, form, progress and toolbox widgets in a multi-column responsive layout.",
        tags:["theme","admin","dashboard","tree"],
        imgUrl:"http://www.bootply.com/assets/templates/85861.png",
        downloadUrl:"http://bootply.com/download/85861",
        sourceUrl:"http://bootply.com/85861",
        previewUrl:"http://bootply.com/render/85861",
        author:"Bootply.com"
    },
	{
        id:"69913",
        name:"Bootable",
        title:"Bootable",
        short:"3-column with sidebar",
        full:"A popular social media and tech news site was the inspiration for this 3-column sticky scrolling design.",
        tags:["news","theme","affix"],
        imgUrl:"http://www.bootply.com/assets/templates/69913.png",
        downloadUrl:"http://bootply.com/download/69913",
        sourceUrl:"http://bootply.com/69913",
        previewUrl:"http://bootply.com/render/69913",
        author:"Bootply.com"
    },
	{
        id:"85746",
        name:"CapitalCity",
        title:"Capital City",
        short:"One page scrolling template",
        full:"Single page app style template with smooth scrolling nav, and centered content that make it ideal for a app launch or startup page.",
        tags:["theme","parallax","scroll"],
        imgUrl:"http://www.bootply.com/assets/templates/85746.png",
        downloadUrl:"http://bootply.com/download/85746",
        sourceUrl:"http://bootply.com/85746",
        previewUrl:"http://bootply.com/render/85746",
        author:"Bootply.com"
    },
	{
        id:"69873",
        name:"Flathood",
        title:"Flathood",
        short:"Bold 2-column layout",
        full:"A popular tech news site was the inspiration for this 2-column bold, bright design. This template uses the Bootstrap affix plugin to pin the sidebar after scrolling past the top header.",
        tags:["fixed","affix","sidebar","news","theme"],
        imgUrl:"http://www.bootply.com/assets/templates/69873.png",
        downloadUrl:"http://bootply.com/download/69873",
        sourceUrl:"http://bootply.com/69873",
        previewUrl:"http://bootply.com/render/69873",
        author:"Bootply.com"
    },
	{
        id:"85850",
        name:"Admin",
        title:"Admin",
        short:"3 column control panel",
        full:"This is a starter template for a admin, control panel or dashboard. This template has a collapsible tree menu, and a variety of panels that can be used as dashboard widgets.",
        tags:["starter","admin","dashboard","theme","tree"],
        imgUrl:"http://www.bootply.com/assets/templates/85850.png",
        downloadUrl:"http://bootply.com/download/85850",
        sourceUrl:"http://bootply.com/85850",
        previewUrl:"http://bootply.com/render/85850",
        author:"Bootply.com"
    },
	{
        id:"86704",
        name:"Basis",
        title:"Basis",
        short:"Minimal fixed sidebar layout",
        full:"A fresh, minimalist design that features a fixed left panel, and scrolling right content panel that works well for articles and blog posts.",
        tags:["theme","fixed","sidebar","minimal"],
        imgUrl:"http://www.bootply.com/assets/templates/86704.png",
        downloadUrl:"http://bootply.com/download/86704",
        sourceUrl:"http://bootply.com/86704",
        previewUrl:"http://bootply.com/render/86704",
        author:"Bootply.com"
    },
	{
        id:"85657",
        name:"Greenfield",
        title:"Greenfield",
        short:"Bold single page scroller",
        full:"Ideal for a landing page, this template includes a smooth scrolling nav, and fixed background images to create a parallax style affect. The top nav menu items are activated as the content sections are scrolled to.",
        tags:["theme","launch","scrollspy","scroll","smooth"],
        imgUrl:"http://www.bootply.com/assets/templates/85657.png",
        downloadUrl:"http://bootply.com/download/85657",
        sourceUrl:"http://bootply.com/85657",
        previewUrl:"http://bootply.com/render/85657",
        author:"Bootply.com"
    },
	{
        id:"88105",
        name:"Darkside",
        title:"Darkside",
        short:"Dark with off-canvas sidebar",
        full:"The deep gray layout features a sidebar drawer menu that responsively collapses off-canvas on smaller devices such as tablets and smartphones.<br>When the sidebar is collapsed, it can be toggled on so that it slides in from the left and consumes 40% of the screen width.<br>This template also includes a sticky bottom footer that stays at the bottom regardless of content height.",
        tags:["theme","fixed","dark","sidebar","collapse","off-canvas","mobile","toggle","footer","sticky"],
        imgUrl:"http://www.bootply.com/assets/templates/88105.png",
        downloadUrl:"http://bootply.com/download/88105",
        sourceUrl:"http://bootply.com/88105",
        previewUrl:"http://bootply.com/render/88105",
        author:"Bootply.com",
        bootstrapVersion:"3.0.3"
    },
	{
        id:"96266",
        name:"Facebook",
        title:"Facebook",
        short:"Facebook-style collapsing sidebar",
        full:"<p>A Facebook inspired template and theme that features a responsive collapsible off-canvas sidebar.</p><p>When the sidebar is collapsed, it can be toggled with a chevron arrow so that it slides in from the left to 1/3 of the screen width.</p><p>This template also features a navbar search form, status post modal and content cards.</p>",
        tags:["theme","sidebar","facebook","off-canvas","toggle","search","modal"],
        imgUrl:"http://www.bootply.com/assets/templates/96266.png",
        downloadUrl:"http://bootply.com/download/96266",
        sourceUrl:"http://bootply.com/96266",
        previewUrl:"http://bootply.com/render/96266",
        author:"Bootply.com"
    },
	{
        id:"88300",
        name:"5050",
        title:"50-50",
        short:"Full width 2x2 grid",
        full:"A simple layout with fixed header and footer, and a centered 50% height and 50% width 2x2 grid.",
        tags:["theme","background","full","100%"],
        imgUrl:"http://www.bootply.com/assets/templates/88300.png",
        downloadUrl:"http://bootply.com/download/88300",
        sourceUrl:"http://bootply.com/88300",
        previewUrl:"http://bootply.com/render/88300",
        author:"Bootply.com"
    },
	{
        id:"100702",
        name:"HappyScroll",
        title:"Happy Scroll",
        short:"One page parallax style",
        full:"A bold, bright Bootstrap template that features a centered fly-in navbar with sections that activate when scrolling. This template also includes a Google Maps contact section, social media buttons and fixed image background.",
        tags:["fixed","scrollspy","google-maps","map","sections","theme"],
        imgUrl:"http://www.bootply.com/assets/templates/100702.png",
        downloadUrl:"http://bootply.com/download/100702",
        sourceUrl:"http://bootply.com/100702",
        previewUrl:"http://bootply.com/render/100702",
        author:"Bootply.com"
    },
	{
        id:"102931",
        name:"Firm",
        title:"The Firm",
        short:"Clean one page scrolling layout",
        full:"A long scrolling Bootstrap template with centered navbar and multiple vertical sections. The header contains a full screen image carousel with dot navigation. The center navbar attaches once the user scrolls beyond the carousel / slider. This template also includes a modal lightbox thumbnail viewer that is ideal for a portfolio or image gallery. The contact form address drives the integration Google maps location.",
        tags:["theme","scroll","one-page","background","full","google-maps","lightbox","slider","gallery","navbar","affix","contact"],
        imgUrl:"http://www.bootply.com/assets/templates/102931.png",
        downloadUrl:"http://bootply.com/download/102931",
        sourceUrl:"http://bootply.com/102931",
        previewUrl:"http://bootply.com/render/102931",
        author:"Bootply.com"
    }
]