module.exports = 
[
    {
        id:"101004",
        name:"Basic",
        title:"Basic Template",
        short:"The simple vanilla template",
        full:"This is the defacto starter template for Bootstrap 3 that includes a top navigation bar and centered block.",
        tags:["basic","starter"],
        imgUrl:"http://www.bootply.com/assets/templates/101004.png",
        downloadUrl:"http://bootply.com/download/101004",
        sourceUrl:"http://bootply.com/101004",
        previewUrl:"http://bootply.com/render/101004",
        author:"Bootply.com"
    },
    {
        id:"100993",
        name:"Sidebar",
        title:"Sidebar Template",
        short:"Popular left column layout",
        full:"This is a popular 2 column template for Bootstrap 3 that includes a left-side 33% width column, and 66% width content area.",
        tags:["sidebar","starter"],
        imgUrl:"http://www.bootply.com/assets/templates/100993.png",
        downloadUrl:"http://bootply.com/download/100993",
        sourceUrl:"http://bootply.com/100993",
        previewUrl:"http://bootply.com/render/100993",
        author:"Bootply.com"
    },
    {
        id:"94967",
        name:"Fixed_Width",
        title:"Fixed Width Template",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/94967.png",
        downloadUrl:"http://bootply.com/download/94967",
        sourceUrl:"http://bootply.com/94967",
        previewUrl:"http://bootply.com/render/94967",
        author:"Bootply.com"
    },
	{
        id:"75225",
        name:"Fixed Navbar - /assets/templates/75225.png",
        title:"Fixed Navbar",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://bootply.com/assets/templates/75225.png",
        downloadUrl:"http://bootply.com/download/75225",
        sourceUrl:"http://bootply.com/75225",
        previewUrl:"http://bootply.com/render/75225",
        author:"Bootply.com"
    },
    {
        id:"75231",
        name:"Sticky Footer - /assets/templates/75231.png",
        title:"Sticky Footer",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/75231.png",
        downloadUrl:"http://bootply.com/download/75231",
        sourceUrl:"http://bootply.com/75231",
        previewUrl:"http://bootply.com/render/75231",
        author:"Bootply.com"
    },
	{
        id:"73778",
        name:"Grid - /assets/templates/73778.png",
        title:"Grid",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/73778.png",
        downloadUrl:"http://bootply.com/download/73778",
        sourceUrl:"http://bootply.com/73778",
        previewUrl:"http://bootply.com/render/73778",
        author:"Bootply.com"
    },
	{
        id:"100983",
        name:"Affix Sidebar - /assets/templates/100983.png",
        title:"Affix Sidebar",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/100983.png",
        downloadUrl:"http://bootply.com/download/100983",
        sourceUrl:"http://bootply.com/100983",
        previewUrl:"http://bootply.com/render/100983",
        author:"Bootply.com"
    },
	{
        id:"65566",
        name:"Full Example - /assets/templates/65566.png",
        title:"Full Example",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/65566.png",
        downloadUrl:"http://bootply.com/download/65566",
        sourceUrl:"http://bootply.com/65566",
        previewUrl:"http://bootply.com/render/65566",
        author:"Bootply.com"
    },
	{
        id:"101053",
        name:"Complex Navbar - /assets/templates/101053.png",
        title:"Complex Navbar",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/101053.png",
        downloadUrl:"http://bootply.com/download/101053",
        sourceUrl:"http://bootply.com/101053",
        previewUrl:"http://bootply.com/render/101053",
        author:"Bootply.com"
    },
	{
        id:"88026",
        name:"Off-canvas Sidebar - /assets/templates/88026.png",
        title:"Off-canvas Sidebar",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/88026.png",
        downloadUrl:"http://bootply.com/download/88026",
        sourceUrl:"http://bootply.com/88026",
        previewUrl:"http://bootply.com/render/88026",
        author:"Bootply.com"
    },
	{
		id:"97459",
        name:"Portfolio - /assets/templates/97459.png",
        title:"Portfolio",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/97459.png",
        downloadUrl:"http://bootply.com/download/97459",
        sourceUrl:"http://bootply.com/97459",
        previewUrl:"http://bootply.com/render/97459",
        author:"Bootply.com"
    },
	{
        id:"62603",
        name:"Slider - /assets/templates/62603.png",
        title:"Slider",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/62603.png",
        downloadUrl:"http://bootply.com/download/62603",
        sourceUrl:"http://bootply.com/62603",
        previewUrl:"http://bootply.com/render/62603",
        author:"Bootply.com"
    },
	{
        id:"101009",
        name:"Landing Page - /assets/templates/101009.png",
        title:"Landing Page",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/101009.png",
        downloadUrl:"http://bootply.com/download/101009",
        sourceUrl:"http://bootply.com/101009",
        previewUrl:"http://bootply.com/render/101009",
        author:"Bootply.com"
    },
	{
        id:"101498",
        name:"Sign-In - /assets/templates/101498.png",
        title:"Sign-In",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/101498.png",
        downloadUrl:"http://bootply.com/download/101498",
        sourceUrl:"http://bootply.com/101498",
        previewUrl:"http://bootply.com/render/101498",
        author:"Bootply.com"
    },
	{
        id:"96937",
        name:"App - /assets/templates/96937.png",
        title:"App Template",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/96937.png",
        downloadUrl:"http://bootply.com/download/96937",
        sourceUrl:"http://bootply.com/96937",
        previewUrl:"http://bootply.com/render/96937",
        author:"Bootply.com"
    },
	{
        id:"101499",
        name:"Blog - /assets/templates/101499.png",
        title:"Blog",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/101499.png",
        downloadUrl:"http://bootply.com/download/101499",
        sourceUrl:"http://bootply.com/101499",
        previewUrl:"http://bootply.com/render/101499",
        author:"Bootply.com"
    },
	{
        id:"101506",
        name:"Portal - /assets/templates/101506.png",
        title:"Portal",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/101506.png",
        downloadUrl:"http://bootply.com/download/101506",
        sourceUrl:"http://bootply.com/101506",
        previewUrl:"http://bootply.com/render/101506",
        author:"Bootply.com"
    },
	{
        id:"90113",
        name:"Plus - /assets/templates/90113.png",
        title:"Plus",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/90113.png",
        downloadUrl:"http://bootply.com/download/90113",
        sourceUrl:"http://bootply.com/90113",
        previewUrl:"http://bootply.com/render/90113",
        author:"Bootply.com"
    },
	{
        id:"91970",
        name:"Holo - /assets/templates/91970.png",
        title:"Holo",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://bootply.com/assets/templates/91970.png",
        downloadUrl:"http://bootply.com/download/91970",
        sourceUrl:"http://bootply.com/91970",
        previewUrl:"http://bootply.com/render/91970",
        author:"Bootply.com"
    },
	{
        id:"85779",
        name:"Story - /assets/templates/85779.png",
        title:"Storystrap",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/85779.png",
        downloadUrl:"http://bootply.com/download/85779",
        sourceUrl:"http://bootply.com/85779",
        previewUrl:"http://bootply.com/render/85779",
        author:"Bootply.com"
    },
	{
        id:"85861",
        name:"Dashboard - /assets/templates/85861.png",
        title:"Dashboard",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/85861.png",
        downloadUrl:"http://bootply.com/download/85861",
        sourceUrl:"http://bootply.com/85861",
        previewUrl:"http://bootply.com/render/85861",
        author:"Bootply.com"
    },
	{
        id:"69913",
        name:"Bootable",
        title:"Bootable",
        short:"Pixel-based container layout",
        full:"A popular social media and tech news site was the inspiration for this 3-column sticky scrolling design.",
        tags:["news","theme","affix"],
        imgUrl:"http://www.bootply.com/assets/templates/69913.png",
        downloadUrl:"http://bootply.com/download/69913",
        sourceUrl:"http://bootply.com/69913",
        previewUrl:"http://bootply.com/render/69913",
        author:"Bootply.com"
    },
	{
        id:"85746",
        name:"CapitalCity",
        title:"Capital City",
        short:"One page scrolling paralax",
        full:"Single page app style template with smooth scrolling nav, and centered content that make it ideal for a app launch or startup page.",
        tags:["theme","parallax","scroll"],
        imgUrl:"http://www.bootply.com/assets/templates/85746.png",
        downloadUrl:"http://bootply.com/download/85746",
        sourceUrl:"http://bootply.com/85746",
        previewUrl:"http://bootply.com/render/85746",
        author:"Bootply.com"
    },
	{
        id:"69873",
        name:"Flathood",
        title:"Flathood",
        short:"Bold 2 column layout",
        full:"A popular tech news site was the inspiration for this 2-column bold, bright design.",
        tags:["fixed","affix","sidebar","news","theme"],
        imgUrl:"http://www.bootply.com/assets/templates/69873.png",
        downloadUrl:"http://bootply.com/download/69873",
        sourceUrl:"http://bootply.com/69873",
        previewUrl:"http://bootply.com/render/69873",
        author:"Bootply.com"
    },
	{
        id:"85850",
        name:"Admin",
        title:"Admin",
        short:"3 column control panel",
        full:"This is a starter template for a admin, control panel or dashboard.",
        tags:["starter","admin","dashboard"],
        imgUrl:"http://www.bootply.com/assets/templates/85850.png",
        downloadUrl:"http://bootply.com/download/85850",
        sourceUrl:"http://bootply.com/85850",
        previewUrl:"http://bootply.com/render/85850",
        author:"Bootply.com"
    },
	{
        id:"86704",
        name:"Basis",
        title:"Basis",
        short:"Minimal fixed sidebar layout",
        full:"A fresh, minimalist design that features a fixed left panel, and scrolling right content panel that works well for articles and blog posts.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/86704.png",
        downloadUrl:"http://bootply.com/download/86704",
        sourceUrl:"http://bootply.com/86704",
        previewUrl:"http://bootply.com/render/86704",
        author:"Bootply.com"
    },
	{
        id:"85657",
        name:"Greenfield",
        title:"Greenfield",
        short:"Bold single page scroller",
        full:"Ideal for a landing page, this template includes a smooth scrolling nav, and fixed background images to create a parallax style affect.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/85657.png",
        downloadUrl:"http://bootply.com/download/85657",
        sourceUrl:"http://bootply.com/85657",
        previewUrl:"http://bootply.com/render/85657",
        author:"Bootply.com"
    },
	{
        id:"91970",
        name:"One Page App - /assets/templates/91970.png",
        title:"One Page App",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://bootply.com/assets/templates/91970.png",
        downloadUrl:"http://bootply.com/download/91970",
        sourceUrl:"http://bootply.com/91970",
        previewUrl:"http://bootply.com/render/91970",
        author:"Bootply.com"
    },
	{
        id:"88105",
        name:"Darkside",
        title:"Darkside",
        short:"Dark with off-canvas sidebar",
        full:"The deep gray layout features a sidebar drawer menu that responsively collapse off-canvas a smaller devices.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/88105.png",
        downloadUrl:"http://bootply.com/download/88105",
        sourceUrl:"http://bootply.com/88105",
        previewUrl:"http://bootply.com/render/88105",
        author:"Bootply.com"
    },
	{
        id:"96266",
        name:"Faceboot",
        title:"Faceboot",
        short:"Facebook style collapsing sidebar",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/96266.png",
        downloadUrl:"http://bootply.com/download/96266",
        sourceUrl:"http://bootply.com/96266",
        previewUrl:"http://bootply.com/render/96266",
        author:"Bootply.com"
    },
	{
        id:"88300",
        name:"50 50 - /assets/templates/88300.png",
        title:"50-50",
        short:"Full width 2x2 grid",
        full:"A simple layout with fixed header and footer, and a centered 50% height and 50% width 2x2 grid.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/88300.png",
        downloadUrl:"http://bootply.com/download/88300",
        sourceUrl:"http://bootply.com/88300",
        previewUrl:"http://bootply.com/render/88300",
        author:"Bootply.com"
    },
	{
        id:"100702",
        name:"Happy Scroll",
        title:"Happy Scroll",
        short:"Pixel-based container layout",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/100702.png",
        downloadUrl:"http://bootply.com/download/100702",
        sourceUrl:"http://bootply.com/100702",
        previewUrl:"http://bootply.com/render/100702",
        author:"Bootply.com"
    },
	{
        id:"102931",
        name:"Firm",
        title:"The Firm",
        short:"Clean one page layout ideal for small business or startup",
        full:"Standard Bootstrap uses a fluid or percentage-based container. This template exemplifies a fixed or pixel-based container.",
        tags:["starter","fixed","width"],
        imgUrl:"http://www.bootply.com/assets/templates/102931.png",
        downloadUrl:"http://bootply.com/download/88300",
        sourceUrl:"http://bootply.com/88300",
        previewUrl:"http://bootply.com/render/88300",
        author:"Bootply.com"
    }
]